Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Dr. Nelio Alves
// Descrição   : calculo
// Autor(a)    : Pedro Henrique
// Data atual  : 21/11/2022
Var
// Seção de Declarações das variáveis 
   x, y, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor de X: ")
   leia(x)
   escreva("Digite o valor de Y: ")
   leia(y)
   soma <- x + y
   escreval("SOMA = ", soma)

Fimalgoritmo